In [1]:
# @title Data manipulation with Python
import pandas as pd

url = 'https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv'
df = pd.read_csv(url)

In [2]:
# @title menampilkan dataset
print("Ukuran dataset:", df.shape)
df.head()
display(df)

Ukuran dataset: (891, 12)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [3]:
# @title melihat missing value
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [4]:
# @title Menghapus Kolom yang tidak relevan untuk pelatihan model
kolom_sampah = ['PassengerId', 'Name', 'Ticket', 'Cabin']
df_bersih = df.drop(columns=kolom_sampah)
df_bersih.head()

   Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         0       3    male  22.0      1      0   7.2500        S
1         1       1  female  38.0      1      0  71.2833        C
2         1       3  female  26.0      0      0   7.9250        S
3         1       1  female  35.0      1      0  53.1000        S
4         0       3    male  35.0      0      0   8.0500        S

In [5]:
# @title Menangani missing value pada kolom age
median_umur = df_bersih['Age'].median()
df_bersih['Age'] = df_bersih['Age'].fillna(median_umur)

In [6]:
# @title Menghapus sisa baris yang masih memiliki missing values (misal ada 2 baris kosong di
# kolom 'Embarked')
df_bersih = df_bersih.dropna()

In [7]:
# @title Melihat kembali sum of missing value
# tulis lagi yak gimana lihatnya 🤭
# @title Melihat kembali sum of missing value
df_bersih.isnull().sum()

Survived    0
Pclass      0
Sex         0
Age         0
SibSp       0
Parch       0
Fare        0
Embarked    0
dtype: int64

In [8]:
# @title One hot encoding kalo kategoorikal
df_final = pd.get_dummies(df_bersih, columns=['Sex', 'Embarked'], drop_first=True)
df_final.head()

,Survived,Pclass,Age,SibSp,Parch,Fare,Sex_male,Embarked_Q,Embarked_S
0,0,3,22.0,1,0,7.2500,True,False,True
1,1,1,38.0,1,0,71.2833,False,False,False
2,1,3,26.0,0,0,7.9250,False,False,True
3,1,1,35.0,1,0,53.1000,False,False,True
4,0,3,35.0,0,0,8.0500,True,False,True

In [9]:
# @title normalisasi menggunakan min max scaler
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
df_scaled = pd.DataFrame(scaler.fit_transform(df_final), columns=df_final.columns)

df_scaled.head()

ModuleNotFoundError: No module named 'sklearn'

In [10]:
# @title tampilkan kembali hasil data final
display(df_scaled)
print("Ukuran dataset setelah preprocessing:", df_scaled.shape)

NameError: name 'df_scaled' is not defined